<?php

namespace App\Presentations;

use Eideos\Framework\Presentations\pst_selectarray;

class pst_cargos_camara extends pst_selectarray {

    protected $values = [
        'PRESIDENTE' => 'PRESIDENTE',
        'VICEPRESIDENTE' => 'VICEPRESIDENTE',
        'VICEPRESIDENTE II' => 'VICEPRESIDENTE II',
        'VICEPRESIDENTE III' => 'VICEPRESIDENTE III',
        'VICEPRESIDENTE IV' => 'VICEPRESIDENTE IV',
        'SECRETARIO' => 'SECRETARIO',
        'SECRETARIO DEL INTERIOR' => 'SECRETARIO DEL INTERIOR',
        'PROSECRETARIO' => 'PROSECRETARIO',
        'PROSECRETARIO II' => 'PROSECRETARIO II',
        'PROSECRETARIO DEL INTERIOR' => 'PROSECRETARIO DEL INTERIOR',
        'SECRETARIO DE HACIENDA' => 'SECRETARIO DE HACIENDA',
        'SECRETARIO DE ORGANIZACIÓN' => 'SECRETARIO DE ORGANIZACIÓN',
        'SECRETARIO DE RELACIONES INSTITUCIONALES' => 'SECRETARIO DE RELACIONES INSTITUCIONALES',
        'SECRETARIO DE RELACIONES PUBLICAS' => 'SECRETARIO DE RELACIONES PUBLICAS',
        'SECRETARIO DE PRENSA' => 'SECRETARIO DE PRENSA',
        'SECRETARIO DE RELACIONES INTERNACIONALES' => 'SECRETARIO DE RELACIONES INTERNACIONALES',
        'SECRETARIO GREMIAL COMERCIO' => 'SECRETARIO GREMIAL COMERCIO',
        'SECRETARIO ADJUNTO COMERCIO' => 'SECRETARIO ADJUNTO COMERCIO',
        'SECRETARIO DE CAPACITACION' => 'SECRETARIO DE CAPACITACION',
        'SECRETARIO DE CENTROS COMERCIALES ABIERTOS' => 'SECRETARIO DE CENTROS COMERCIALES ABIERTOS',
        'SECRETARIO GREMIAL DE INDUSTRIA' => 'SECRETARIO GREMIAL DE INDUSTRIA',
        'SECRETARIO DE CAPACITACION INDUSTRIA' => 'SECRETARIO DE CAPACITACION INDUSTRIA',
        'SECRETARIO ADJUNTO DE INDUSTRIA' => 'SECRETARIO ADJUNTO DE INDUSTRIA',
        'SECRETARIO DE SEGURIDAD' => 'SECRETARIO DE SEGURIDAD',
        'SECRETARIA DE CULTURA' => 'SECRETARIA DE CULTURA',
        'SECRETARIO DE SERVICIOS' => 'SECRETARIO DE SERVICIOS',
        'SECRETARIO DE CONSTRUCCION Y SERVICIOS INMOBILIARIOS' => 'SECRETARIO DE CONSTRUCCION Y SERVICIOS INMOBILIARIOS',
        'SECRETARIO DE PLANEAMIENTO' => 'SECRETARIO DE PLANEAMIENTO',
        'SECRETARIO DE ACCION SOCIAL' => 'SECRETARIO DE ACCION SOCIAL',
        'SECRETARIO DE DESARROLLO SUSTENTABLE' => 'SECRETARIO DE DESARROLLO SUSTENTABLE',
        'SECRETARIO DE COMERCIO EXTERIOR' => 'SECRETARIO DE COMERCIO EXTERIOR',
        'SECRETARIA ADJUNTA DE COMERCIO EXTERIOR' => 'SECRETARIA ADJUNTA DE COMERCIO EXTERIOR',
        'SECRETARIO DE TURISMO' => 'SECRETARIO DE TURISMO',
        'SECRETARIO DE HABILITACIONES' => 'SECRETARIO DE HABILITACIONES',
        'SECRETARIO DE SALUD' => 'SECRETARIO DE SALUD',
        'SECRETARIO DE MOVILIDAD Y TRANSPORTE' => 'SECRETARIO DE MOVILIDAD Y TRANSPORTE',
        'SECRETARIO DE DEPORTES' => 'SECRETARIO DE DEPORTES',
        'SECRETARIA DE JOVENES EMPRESARIOS' => 'SECRETARIA DE JOVENES EMPRESARIOS',
        'SECRETARIA DE MUJERES EMPRESARIAS' => 'SECRETARIA DE MUJERES EMPRESARIAS',
        'SECRETARIO DE PUERTOS' => 'SECRETARIO DE PUERTOS',
        'SECRETARIO DE LA CONSTRUCCION PYME' => 'SECRETARIO DE LA CONSTRUCCION PYME',
        'TESORERO' => 'TESORERO',
        'PROTESORERO' => 'PROTESORERO',
        'PROTESORERO II' => 'PROTESORERO II',
        'VOCALES' => 'VOCALES',
        'TRIBUNAL ARBITRAL - Titular' => 'TRIBUNAL ARBITRAL - Titular',
        'TRIBUNAL ARBITRAL - Suplente' => 'TRIBUNAL ARBITRAL - Suplente',
        'COMISION REVISORA DE CUENTAS - Titular' => 'COMISION REVISORA DE CUENTAS - Titular',
        'COMISION REVISORA DE CUENTAS - Suplente' => 'COMISION REVISORA DE CUENTAS - Suplente',
    ];

}
