<?php

namespace App\Presentations;

use Eideos\Framework\Presentations\pst_selectarray;

class pst_cargos_sindicato extends pst_selectarray {

    protected $values = [
        'SECRETARIA GENERAL/PRESIDENTE' => 'SECRETARIA GENERAL/PRESIDENTE',
        'SECRETARIA ADJUNTA O SUBSECRETARIA GENERAL' => 'SECRETARIA ADJUNTA O SUBSECRETARIA GENERAL',
        'SECRETARIA GREMIAL' => 'SECRETARIA GREMIAL',
        'SECRETARIA ADMINISTRATIVA' => 'SECRETARIA ADMINISTRATIVA',
        'SECRETARIA DE ORGANIZACIÓN' => 'SECRETARIA DE ORGANIZACIÓN',
        'SECRETARIA DE FINANZAS' => 'SECRETARIA DE FINANZAS',
        'TESORERO' => 'TESORERO',
        'PROTESORERO' => 'PROTESORERO',
        'SECRETARIA DE ACTAS' => 'SECRETARIA DE ACTAS',
        'SECRETARIA DE ASISTENCIA SOCIAL/ACCION SOCIAL' => 'SECRETARIA DE ASISTENCIA SOCIAL/ACCION SOCIAL',
        'SECRETARIA DE PRENSA Y PROPAGANDA' => 'SECRETARIA DE PRENSA Y PROPAGANDA',
        'SECRETARIA DE RELACIONES INTERNACIONALES' => 'SECRETARIA DE RELACIONES INTERNACIONALES',
        'SECRETARIA DE RELACIONES INSTITUCIONALES' => 'SECRETARIA DE RELACIONES INSTITUCIONALES',
        'SECRETARIA DE ASUNTOS PREVISIONALES' => 'SECRETARIA DE ASUNTOS PREVISIONALES',
        'SECRETARIA DE ESTADISTICA Y ANALISIS' => 'SECRETARIA DE ESTADISTICA Y ANALISIS',
        'SECRETARIA DE TURISMO' => 'SECRETARIA DE TURISMO',
        'SECFETARIA DE DEPORTES Y RECREACION' => 'SECFETARIA DE DEPORTES Y RECREACION',
        'SECRETARIA DE CULTURA' => 'SECRETARIA DE CULTURA',
        'SECRETARIA DE FORMACION Y CAPACITACION' => 'SECRETARIA DE FORMACION Y CAPACITACION',
        'SECRETARIA DE LA MUJER Y PROTECCION DE LA NIÑEZ' => 'SECRETARIA DE LA MUJER Y PROTECCION DE LA NIÑEZ',
        'SECRETARIA DE VIVIENDA' => 'SECRETARIA DE VIVIENDA',
        'SECRETARIA DE HIGIENE, MEDICINA Y SEGURIDAD EN EL TRABAJO' => 'SECRETARIA DE HIGIENE, MEDICINA Y SEGURIDAD EN EL TRABAJO',
        'SECRETARAIA DE ASUNTOS LEGISLATIVOS' => 'SECRETARAIA DE ASUNTOS LEGISLATIVOS',
        'SECRETARIA DE DERECHOS HUMANOS' => 'SECRETARIA DE DERECHOS HUMANOS',
        'SECRERTARIA DE DESARROLLO HUMANO' => 'SECRERTARIA DE DESARROLLO HUMANO',
        'SECRETARIA DE INTERIOR' => 'SECRETARIA DE INTERIOR',
        'SECRETARIA DE ASUNTOS LABORALES' => 'SECRETARIA DE ASUNTOS LABORALES',
        'SECRETARIA DE LA JUVENTUD' => 'SECRETARIA DE LA JUVENTUD',
        'SECRETARIA DE MUTUAL Y COOPERATIVAS' => 'SECRETARIA DE MUTUAL Y COOPERATIVAS',
        'SECRETARIA DE REDES SOCIALES Y LAS TTECNOLOGIA DE LA COMUNICACION' => 'SECRETARIA DE REDES SOCIALES Y LAS TTECNOLOGIA DE LA COMUNICACION',
        'VOCAL TITULAR' => 'VOCAL TITULAR',
        'VOCAL SUPLENTE' => 'VOCAL SUPLENTE',
        'REVISOR DE CUENTAS TITULAR ' => 'REVISOR DE CUENTAS TITULAR ',
        'REVISOR DE CUENTAS SUPLENTE ' => 'REVISOR DE CUENTAS SUPLENTE ',
    ];

}
